const fallbackScholarships = [
  {
    _id: "sch-1",
    title: "National Scholarship Portal",
    provider: "Ministry of Education",
    description: "A single portal for applying to several central and state scholarship schemes.",
    amount: 12000,
    eligibility: "Students enrolled in recognized institutions with valid income and academic documents.",
    incomeLimit: 500000,
    minimumCGPA: 7,
    state: "All India",
    category: "Scholarship",
    course: "All Courses",
    gender: "Any",
    deadline: new Date("2027-12-31T23:59:59.000Z"),
    requiredDocuments: ["Aadhaar card", "Income certificate", "Bonafide certificate", "Marksheet"],
    applyLink: "https://scholarships.gov.in",
    isActive: true,
  },
  {
    _id: "sch-2",
    title: "Pragati Scholarship for Girls",
    provider: "AICTE",
    description: "Scholarship support for meritorious girl students pursuing technical education.",
    amount: 50000,
    eligibility: "Girl students with a family income below the prescribed limit and admission in a technical course.",
    incomeLimit: 800000,
    minimumCGPA: 6,
    state: "All India",
    category: "Scholarship",
    course: "Engineering",
    gender: "Female",
    deadline: new Date("2027-10-31T23:59:59.000Z"),
    requiredDocuments: ["Admission proof", "Income certificate", "Aadhaar card", "Caste certificate if applicable"],
    applyLink: "https://aicte-india.org",
    isActive: true,
  },
  {
    _id: "sch-3",
    title: "Kisan Credit Card Support Scheme",
    provider: "Department of Agriculture",
    description: "Financial assistance and low-interest credit support for farmers and agriculturists.",
    amount: 75000,
    eligibility: "Farmers and cultivators with valid land records and identity proofs.",
    incomeLimit: 0,
    minimumCGPA: 0,
    state: "All India",
    category: "Agriculture",
    course: "All Courses",
    gender: "Any",
    deadline: new Date("2027-09-30T23:59:59.000Z"),
    requiredDocuments: ["Land records", "Aadhaar card", "Bank account details"],
    applyLink: "https://agri.gov.in",
    isActive: true,
  },
  {
    _id: "sch-4",
    title: "Ayushman Bharat Health Scheme",
    provider: "Ministry of Health",
    description: "Health insurance coverage for eligible households and vulnerable families.",
    amount: 500000,
    eligibility: "Families listed under the eligible health benefit categories.",
    incomeLimit: 600000,
    minimumCGPA: 0,
    state: "All India",
    category: "Health",
    course: "All Courses",
    gender: "Any",
    deadline: new Date("2028-03-31T23:59:59.000Z"),
    requiredDocuments: ["Ration card", "Aadhaar card", "Income certificate"],
    applyLink: "https://pmjay.gov.in",
    isActive: true,
  },
  {
    _id: "sch-5",
    title: "PM Awas Yojana Housing Benefit",
    provider: "Ministry of Housing",
    description: "Housing support for eligible rural and urban low-income households.",
    amount: 150000,
    eligibility: "Low-income families that are eligible for housing support under the scheme.",
    incomeLimit: 300000,
    minimumCGPA: 0,
    state: "All India",
    category: "Housing",
    course: "All Courses",
    gender: "Any",
    deadline: new Date("2027-11-30T23:59:59.000Z"),
    requiredDocuments: ["Aadhaar card", "Address proof", "Income certificate"],
    applyLink: "https://pmay-urban.gov.in",
    isActive: true,
  },
  {
    _id: "sch-6",
    title: "Startup India Seed Fund",
    provider: "Department for Promotion of Industry and Internal Trade",
    description: "Support for innovative startups and entrepreneurs building scalable solutions.",
    amount: 2000000,
    eligibility: "Recognized startups with a valid business plan and registration documents.",
    incomeLimit: 0,
    minimumCGPA: 0,
    state: "All India",
    category: "Business",
    course: "All Courses",
    gender: "Any",
    deadline: new Date("2027-08-31T23:59:59.000Z"),
    requiredDocuments: ["Startup registration", "Business plan", "PAN card"],
    applyLink: "https://www.startupindia.gov.in",
    isActive: true,
  },
];

const cloneScholarship = (scholarship) => ({
  ...scholarship,
  _id: scholarship._id?.toString?.() || scholarship._id,
  deadline: scholarship.deadline ? new Date(scholarship.deadline) : null,
});

const getFallbackScholarships = () => fallbackScholarships.map(cloneScholarship);

const getFallbackScholarshipById = (id) => {
  const match = fallbackScholarships.find((item) => item._id.toString() === id.toString());
  return match ? cloneScholarship(match) : null;
};

module.exports = {
  getFallbackScholarships,
  getFallbackScholarshipById,
};
